# bindings/rust/zrraw/Cargo.toml
[package]
name = "zrraw"
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
zrraw-sys = { path = "../zrraw-sys" }
image = "0.25.6"
thiserror.workspace = true
libloading = "0.8.8"

[dev-dependencies]
tempfile = "3.0"
