# bindings/rust/zrraw/Cargo.toml
[package]
name = "zrraw"
version = "0.1.0"
edition = "2024"

[dependencies]
zrraw-sys = { path = "../zrraw-sys" }
image = "0.25.6"
thiserror = "2.0.12"
libloading = "0.8.8"

[dev-dependencies]
tempfile = "3.0"
